export const Questions = [
    {
        prompt: 'What is 1+ 3',
        optionA: '3',
        optionB: '7',
        optionC: '5',
        optionD: '4',
        answer: 'optionD',
    },
    {
        prompt: 'Which of this is not a programming language?',
        optionA: 'Python',
        optionB: 'JavaScript',
        optionC: 'MC-03',
        optionD: 'Java',
        answer: 'optionC',
    },
    {
        prompt: 'Which of this is not a javascript framework?',
        optionA: 'React',
        optionB: 'Angular',
        optionC: 'Vue',
        optionD: 'Java',
        answer: 'optionD',
    },
    {
        prompt: 'Which is the Streaming Platform?',
        optionA: 'Twitter',
        optionB: 'Twitch',
        optionC: 'Google',
        optionD: 'Robinhood',
        answer: 'optionB',
    },
    {
        prompt: 'How many bones are in human body?',
        optionA: '206',
        optionB: '213',
        optionC: '207',
        optionD: '200',
        answer: 'optionA',
    },
];
